version: '3.7'
services:
    gateway_api:
      container_name: gateway_api
      build:
        context: ""
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      entrypoint: /app/docker-compose/api-entrypoint.sh
