name: Linters
on: [push]

jobs:
  linter:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install nox
    - name: Poetry Fix
      run: pip install poetry==1.1.8
    - name: Run cop session
      run: nox --sessions cop
